name: auto-deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Set up SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p $HOME/.ssh
        cat <<< $SSH_PRIVATE_KEY > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -H stjohnscccc.org >> ~/.ssh/known_hosts

    - name: Deploy
      run: git push chandler@stjohnscccc.org:/var/www/stjohnscccc.org/www
